import ImgRing from '../assets/ImgRing.jpg'
import ImgEarring from '../assets/ImgEarring.jpg'
import Img3 from '../assets/Img3.jpg'
import Img7 from '../assets/Img7.jpg'
import Img6 from '../assets/Img6.jpg'
import ImgBracelet2 from '../assets/ImgBracelet2.jpg'
import ImgNecklace2 from '../assets/ImgNecklace2.jpg'
import ImgNecklace3 from '../assets/ImgNecklace3.jpg'

export const products = [
    { id: 1, name: 'Ring 1', category: 'rings', img: ImgRing, description: ' Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque facilisis feugiat elit, id posuere quam ornare sed. Curabitur at turpis malesuada, maximus urna quis, dignissim justo. Curabitur in lacus vel mauris facilisis ornare. Sed tincidunt, lectus a consectetur pharetra, mi quam efficitur risus, nec tincidunt neque ante eget velit. Donec nisl tellus, molestie sit amet metus sit amet, accumsan consequat eros. Proin laoreet mauris elit, eu efficitur felis tristique tristique. Proin dictum dignissim ipsum, vulputate bibendum metus mattis non. Maecenas vel ex luctus sem iaculis elementum vitae nec nunc.' },
    {
        id: 2, name: 'Earring 1', category: 'earrings', img: ImgEarring, description:
            'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam eu neque eget massa gravida consectetur eget id nunc. Sed a augue ipsum. Praesent pharetra velit elit, vel efficitur mi euismod eget. Donec fringilla mauris libero, et posuere eros imperdiet vitae. Curabitur dapibus vulputate facilisis. Nam vitae interdum nisi. Duis sollicitudin facilisis purus eget placerat. Nunc iaculis ornare tristique. Quisque semper ex vitae nulla sodales, suscipit gravida felis vehicula. Mauris egestas molestie volutpat. Vestibulum nisi magna, pulvinar id condimentum at, blandit ac turpis. Mauris lorem quam, vehicula vel ligula eget, ullamcorper iaculis leo. '
    },
    { id: 4, name: 'Bracelet 1', category: 'bracelets', img: Img7, description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent vestibulum accumsan tincidunt. Sed eget ipsum nec tellus pretium dapibus. Aliquam vulputate semper luctus. Sed vestibulum scelerisque velit ut sollicitudin. Quisque faucibus ut nulla sed fermentum. Integer et arcu lacinia, congue tellus eu, venenatis ipsum. Nam leo eros, rutrum in mauris et, imperdiet eleifend arcu. Nullam nibh magna, tincidunt sit amet elementum vitae, auctor ut tellus. Nullam et ex ipsum.' },
    { id: 5, name: 'bracelet 2', category: 'bracelets', img: Img6, description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed non convallis arcu, quis egestas justo. Interdum et malesuada fames ac ante ipsum primis in faucibus. Donec in maximus ipsum. Donec consectetur tempus nibh, a convallis tellus bibendum at. Nunc ac pharetra ligula. Praesent semper, ligula sed iaculis congue, nibh lacus placerat elit, ut ultricies lorem erat a lorem. Curabitur sed venenatis tortor, eu convallis magna. Phasellus quis sollicitudin augue, ac laoreet nisi. Sed placerat sed ipsum dignissim aliquam. Pellentesque ultricies, felis eget lacinia efficitur, ex eros mattis ante, in luctus purus nisi vel enim. Nunc porta volutpat sem.' },
    { id: 6, name: 'Necklace 1', category: 'necklaces', img: ImgNecklace2, description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas nulla lorem, ultrices non consequat quis, pellentesque quis nunc. Nulla vitae odio sed orci tincidunt ultricies ut bibendum ex. Donec eu mollis enim. Vestibulum eu velit tellus. Curabitur vel dui id sem laoreet vulputate at id purus. Nullam mollis nisl nec leo posuere viverra. In interdum, erat non molestie pretium, ex dui pretium dui, eget luctus enim mauris vitae sem.' },
    { id: 7, name: 'Bracelet 2', category: 'bracelets', img: ImgBracelet2, description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum a egestas mauris, eget semper nisl. Praesent ut risus sit amet purus consectetur faucibus. Pellentesque sem nisi, convallis eget ultrices eget, mattis at tortor. Etiam dolor erat, vehicula vitae dignissim nec, ultrices eget risus. Interdum et malesuada fames ac ante ipsum primis in faucibus. Integer et augue sed erat luctus cursus. Nam maximus, nisl vestibulum tristique vehicula, turpis tortor volutpat velit, sit amet elementum nulla est et enim. Suspendisse potenti. Donec malesuada dictum sapien, ac eleifend nulla elementum at. Donec tempus non lectus eu semper. Sed blandit imperdiet sollicitudin. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.' },
    { id: 8, name: 'Necklace 2', category: 'necklaces', img: ImgNecklace3, description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus dictum id sem in pellentesque. Cras auctor nibh nisl, ut condimentum elit porttitor quis. In nisl elit, efficitur vitae efficitur ac, pretium sit amet metus. Vivamus sapien enim, ultricies eget bibendum ac, mollis at ligula. Fusce rhoncus eros ante, at iaculis est blandit at. Sed at sapien hendrerit, fringilla tortor nec, mattis justo. Nunc scelerisque ligula a urna vestibulum, nec sodales lacus commodo. Suspendisse convallis ullamcorper hendrerit. Aliquam velit erat, vehicula nec pulvinar non, feugiat nec est.' },
    { id: 9, name: 'Ring 2', category: 'rings', img: Img3, description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus dictum id sem in pellentesque. Cras auctor nibh nisl, ut condimentum elit porttitor quis. In nisl elit, efficitur vitae efficitur ac, pretium sit amet metus. Vivamus sapien enim, ultricies eget bibendum ac, mollis at ligula. Fusce rhoncus eros ante, at iaculis est blandit at. Sed at sapien hendrerit, fringilla tortor nec, mattis justo. Nunc scelerisque ligula a urna vestibulum, nec sodales lacus commodo. Suspendisse convallis ullamcorper hendrerit. Aliquam velit erat, vehicula nec pulvinar non, feugiat nec est.' },
];